#!/usr/bin/env node
/* Cross-checks every mockup's contract JSON against tools/inventory.json
   (all REST routes + Socket.IO events from code). Fails if any inventory item is
   neither bound to a screen nor marked noUi. With --write, regenerates the
   coverage matrix inside docs/plans/ui-v2-mockups.md between
   <!-- coverage:start --> and <!-- coverage:end -->.
   Usage: node mockups/v2/tools/coverage.js [--write] [--unknown] */
'use strict';
const fs = require('fs');
const path = require('path');
const V2 = path.resolve(__dirname, '..');
const REPO = path.resolve(V2, '../..');
const DOC = path.join(REPO, 'docs/plans/ui-v2-mockups.md');
const inv = JSON.parse(fs.readFileSync(path.join(__dirname, 'inventory.json'), 'utf8'));
const args = process.argv.slice(2);

const norm = (p) => p.split('?')[0].replace(/\{[^}]+\}/g, ':x').replace(/:[A-Za-z_]\w*(\(\*\))?/g, ':x').replace(/\/+$/, '') || '/';

// Load contracts
const screens = [];
for (const d of ['app', 'admin']) {
  for (const f of fs.readdirSync(path.join(V2, d)).filter((x) => x.endsWith('.html')).sort()) {
    const html = fs.readFileSync(path.join(V2, d, f), 'utf8');
    const m = html.match(/<script type="application\/json" id="contract">([\s\S]*?)<\/script>/);
    const title = (html.match(/<title>([^<·]+)/) || [, f])[1].trim();
    if (!m) { console.log(`WARN ${d}/${f}: no contract`); continue; }
    let c; try { c = JSON.parse(m[1]); } catch (e) { console.log(`FAIL ${d}/${f}: contract JSON invalid: ${e.message}`); process.exitCode = 1; continue; }
    screens.push({ id: `${d}/${f}`, title, c });
  }
}

// REST coverage
const restHits = new Map(); const unknown = new Map();
const items = inv.rest.map((r) => (typeof r === 'string' ? { p: r } : r)).map((r) => ({ ...r, n: norm(r.p.split('#')[0]) })).map((r) => ({ ...r, re: new RegExp('^' + r.n.replace(/[.+?^${}()|[\]\\]/g, '\\$&').replace(/:x/g, '[^/]+') + '$') }));
const wildcard = items.filter((i) => i.n.endsWith('/*'));
for (const s of screens) for (const r of s.c.rest || []) {
  const n = norm(r.p);
  let hit = items.find((i) => i.n === n);
  if (!hit) hit = items.find((i) => i.re.test(n));
  if (!hit) hit = wildcard.find((i) => n.startsWith(i.n.slice(0, -1)));
  if (hit) { if (!restHits.has(hit.n)) restHits.set(hit.n, new Set()); restHits.get(hit.n).add(s.id); }
  else { if (!unknown.has(n)) unknown.set(n, new Set()); unknown.get(n).add(s.id); }
}
// Socket coverage
const sockHits = new Map();
for (const s of screens) for (const ns of s.c.socket || []) {
  for (const dir of ['on', 'emit']) for (const e of ns[dir] || []) {
    const k = `${ns.ns}|${dir}|${e.e}`; if (!sockHits.has(k)) sockHits.set(k, new Set()); sockHits.get(k).add(s.id);
  }
}

let missing = 0; const rows = { rest: [], sock: [] };
for (const i of items) {
  const hit = restHits.get(i.n);
  if (!hit && !i.noUi) { console.log(`MISSING REST ${i.p}`); missing++; }
  rows.rest.push({ p: i.p, screens: hit ? [...hit] : [], noUi: i.noUi });
}
for (const [ns, def] of Object.entries(inv.sockets)) for (const dir of ['on', 'emit']) for (const e of def[dir]) {
  const hit = sockHits.get(`${ns}|${dir}|${e}`); const noUi = def.noUi && def.noUi[e];
  if (!hit && !noUi) { console.log(`MISSING SOCKET ${ns} ${dir === 'on' ? 'S→C' : 'C→S'} ${e}`); missing++; }
  rows.sock.push({ ns, dir, e, screens: hit ? [...hit] : [], noUi });
}
const unknownSock = [];
for (const k of sockHits.keys()) { const [ns, dir, e] = k.split('|'); const def = inv.sockets[ns]; if (!def || !def[dir].includes(e)) unknownSock.push(k); }

if (args.includes('--unknown') || unknown.size || unknownSock.length) {
  if (unknown.size) console.log(`\nINFO ${unknown.size} contract REST path(s) not in inventory (proposed or mistyped):`);
  for (const [n, s] of unknown) console.log(`  ${n}  ← ${[...s].join(', ')}`);
  if (unknownSock.length) console.log(`\nINFO socket events in contracts not in inventory:\n  ${unknownSock.join('\n  ')}`);
}
const restCovered = rows.rest.filter((r) => r.screens.length).length;
const sockCovered = rows.sock.filter((r) => r.screens.length).length;
console.log(`\nREST: ${restCovered}/${rows.rest.length} bound to a screen, ${rows.rest.filter((r) => !r.screens.length && r.noUi).length} marked no-UI · Socket: ${sockCovered}/${rows.sock.length} bound, ${rows.sock.filter((r) => !r.screens.length && r.noUi).length} no-UI · ${screens.length} screens · ${missing} missing`);

if (args.includes('--write')) {
  const link = (id) => `[${id.replace(/\.html$/, '')}](../../mockups/v2/${id})`;
  const mod = (p) => (p.startsWith('/xrpc') || p.startsWith('/.well-known') ? '/atproto (origin root)' : '/' + p.split('/')[1]);
  let md = `_Generated by \`node mockups/v2/tools/coverage.js --write\` from each screen's contract JSON and \`mockups/v2/tools/inventory.json\`. Do not edit by hand._\n\n`;
  md += `**${restCovered} of ${rows.rest.length} REST routes** are bound to at least one screen and the other ${rows.rest.length - restCovered} are marked no-UI with a reason. **${sockCovered} of ${rows.sock.length} Socket.IO events** are bound; the rest are marked no-UI. ${screens.length} screens in total.\n\n`;
  md += `### Socket.IO events → screens\n\n| Namespace | Dir | Event | Screens / reason |\n|---|---|---|---|\n`;
  for (const r of rows.sock) md += `| \`${r.ns}\` | ${r.dir === 'on' ? 'S→C' : 'C→S'} | \`${r.e}\` | ${r.screens.length ? r.screens.map(link).join(', ') : '_no UI: ' + r.noUi + '_'} |\n`;
  md += `\n### REST routes → screens\n`;
  let cur = null;
  for (const r of rows.rest) {
    const m = mod(r.p);
    if (m !== cur) { md += `\n#### \`${m}\`\n\n| Route | Screens / reason |\n|---|---|\n`; cur = m; }
    md += `| \`${r.p}\` | ${r.screens.length ? r.screens.map(link).join(', ') : '_no UI: ' + r.noUi + '_'} |\n`;
  }
  if (unknown.size) {
    md += `\n### Endpoints proposed by the mockups (not in code yet)\n\n| Path | Screens |\n|---|---|\n`;
    for (const [n, s] of unknown) md += `| \`${n}\` | ${[...s].map(link).join(', ')} |\n`;
  }
  const doc = fs.readFileSync(DOC, 'utf8');
  const out = doc.replace(/<!-- coverage:start -->[\s\S]*<!-- coverage:end -->/, `<!-- coverage:start -->\n${md}\n<!-- coverage:end -->`);
  fs.writeFileSync(DOC, out);
  console.log(`wrote coverage matrix to ${path.relative(REPO, DOC)}`);
}
process.exit(missing || process.exitCode ? 1 : 0);
